// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRtubUUhqZN5M5eBo1ysy0kmKBMpp59Zg',
    appId: '1:449892615895:web:43af5f69e84e4437fbd292',
    messagingSenderId: '449892615895',
    projectId: 'ctse-online-shopping-store',
    authDomain: 'ctse-online-shopping-store.firebaseapp.com',
    storageBucket: 'ctse-online-shopping-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0aGZD42G8ur1rpxthp3CVm9ogA3hPYQ',
    appId: '1:449892615895:android:3afb14dc8ae3a347fbd292',
    messagingSenderId: '449892615895',
    projectId: 'ctse-online-shopping-store',
    storageBucket: 'ctse-online-shopping-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewOAdUA4lkBdjpA-ukDB2fIJUx1wF4wQ',
    appId: '1:449892615895:ios:eda13733e28587d9fbd292',
    messagingSenderId: '449892615895',
    projectId: 'ctse-online-shopping-store',
    storageBucket: 'ctse-online-shopping-store.appspot.com',
    iosClientId: '449892615895-70q31digpan47lmpjtqdbk3t6nhpe6ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewOAdUA4lkBdjpA-ukDB2fIJUx1wF4wQ',
    appId: '1:449892615895:ios:eda13733e28587d9fbd292',
    messagingSenderId: '449892615895',
    projectId: 'ctse-online-shopping-store',
    storageBucket: 'ctse-online-shopping-store.appspot.com',
    iosClientId: '449892615895-70q31digpan47lmpjtqdbk3t6nhpe6ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingStore',
  );
}
